### PR TITLE
Styled Footer Component 

### PR DESCRIPTION
**Pull request by jibin2706**
Issue #40

### CODE REVIEW

**Comment by jibin2706** [comment]
https://screenshots.firefox.com/UaUL2jtiSvtTFn7S/localhost
For me there is no space at the bottom

**Comment by jibin2706** [comment]
screenshot_2018-04-16_13-35-36

**Comment by jibin2706** [comment]
Oh I understood

**Comment by ezioda004** [comment]
@jibin2706 Yeah, let me know if you are able to resolve it, if not I'll help you out.

**Comment by jibin2706** [comment]
I tried but it is breaking more stuffs

**Comment by SukhjinderArora** [comment]
@jibin2706 try setting margin-bottom of ul to 0 .

**Comment by jibin2706** [comment]
@SukhjinderArora 
I think he was telling that the footer should be at the bottom of the page

**Comment by SukhjinderArora** [comment]
Because the footer has the ul element which has some default bottom margin so I think that's why space is appearing below footer.

**Comment by jibin2706** [comment]
image
After zooming out
margin:0;

**Comment by ezioda004** [comment]
@jibin2706 Seems like there's some conflict due to #41 merge, resolve that and submit the PR again.

**Pull request merged**
