### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by SukhjinderArora**
As per issue #26 added footer
files changed :
footer.css
footer.js
header.css
in header.css all the list-items was targeted by li { } declaration which was affecting list-items in the footer
so changed it to target only list-items within the header.

### CODE REVIEW

**Comment by lalitmee** [comment]
Hey @SukhjinderArora, your commit is conflicting. Please resolve conflicts. :+1: 
Because the PR can only be merged after resolving conflicts. If you need any help, ping us on slack public channel of this project.

**Comment by SukhjinderArora** [comment]
capture

**Comment by SukhjinderArora** [comment]
Hey @lalitmee do I have to develop same footer with Css styles or just html because in the issue it is written that I only have to develop just html, another issue will be created to style the footer?

**Comment by SukhjinderArora** [comment]
I can make more changes to make it look like the mock up but then there will be different issue for that, so if possible when that issue is created please assign it to me. For now I don't want to make any changes.

**Comment by ezioda004** [comment]
@SukhjinderArora Keep an eye out on the issues, we'll be creating new ones almost everyday going forward since we're just starting. However initially we'd like to encourage someone who hasn't contributed to the project yet but if no one comes forward, we'll assign to anyone who asks for it.
That being said, there's room for everyone (for all level of expertise) so not to worry if you don't get the issue assigned to you, there will always be a new one.

**Comment by lalitmee** [comment]
@SukhjinderArora, oh I was thinking that we are in the work of styling the footer. :wink: 
Then it's ok. We will create another issue for styling.

**Pull request merged**
