### PR TITLE
Styled the Sign In and Sign Up forms.

### PR DESCRIPTION
**Pull request by abhishekakade**
Changed input type to email in signin.js.
Made both email and password fields required.
Fixed typos - changed conform to confirm.
Styled Sign In and Sign Up forms in black theme.

### CODE REVIEW

**Comment by abhishekakade** [comment]
@ezioda004 Yeah sure!

**Comment by abhishekakade** [comment]
@ezioda004 please check the latest commit. Let me know if it needs any changes.

**Comment by Vanisha27** [comment]
@abhishekakade Everything looks good. :+1:

**Comment by abhishekakade** [comment]
Thank you @ezioda004, @Vanisha27  :raised_hands:

**Comment by ezioda004** [comment]
Merged. Thank you @abhishekakade for your valuable contribution. 😇

**Pull request merged**
