### PR TITLE
Home Page as per mockup

### PR DESCRIPTION
**Pull request by goss-gowtham**
I've updated Home page as per the mock up by,

1. removing the Blur filter which affected whole navbar and images and replaced with **Opacity for only image** and not the text.

2. Added Underline as per the mockup with line-spacing which enhances the home page.

3. Didn't fix the Horizontal scroll issue as it's assigned to someone else.

image

### CODE REVIEW

**Comment by goss-gowtham** [comment]
Hey @ezioda004 ,
What is SS?
Resolve the conflict in the sense? Can you Elaborate it?

**Comment by abhishekakade** [comment]
@goss-gowtham, 
SS means screen shot. 
Check your pull request for conflicts.

**Comment by goss-gowtham** [comment]
I didn't get any conflicts and I've Screenshot the Change I made already!

**Comment by ezioda004** [comment]
Hi @goss-gowtham, as @abhishekakade mentioned, please add SS of how the page was before. Its easy to look at the changes you've made.
You need to resolve the conflict, synchronize your repo.
Please read our guide on [how to synchronize the fork here](https://github.com/UdacityFrontEndScholarship/quiz-app/blob/master/CONTRIBUTING.md#how-to-sync-your-fork-with-the-main-project-repository-upstream).

**Comment by goss-gowtham** [comment]
image
I've removed the Blur Property used which affected NavBar and Image style, and added Opacity to image only and Not the texts.
Added Underline as per the mockup for the words **Challenge** and **Practice** .
Conflict is resolved, which was raised after merging the last PR from the other guy.

**Comment by goss-gowtham** [comment]
I'm now getting **This branch has no conflicts with the base branch**, With few commits.
Thanks for the review, and expecting more if any.
It is ready to merge!!!

**Pull request merged**
